language: generic

branches:
  only:
    - master
    - develop

stages:
  - name: Build
  - name: Docs
    if: branch = master

jobs:
  include:
    - name: "Linux x84_64"
      stage: Build
      os: linux
      dist: trusty
      sudo: required
      services:
        - docker
      before_install:
        - docker pull rocproject/travis-ubuntu:18.04
        - docker pull rocproject/travis-ubuntu:16.04
        - docker pull rocproject/travis-ubuntu:14.04
        - docker pull rocproject/travis-debian
        - docker pull rocproject/travis-fedora
        - docker pull rocproject/travis-centos
        - docker pull rocproject/travis-min
      script:
        - scripts/travis/docker.sh rocproject/travis-ubuntu:18.04 scripts/travis/linux-x86_64/ubuntu-18.04.sh
        - scripts/travis/docker.sh rocproject/travis-ubuntu:16.04 scripts/travis/linux-x86_64/ubuntu-16.04.sh
        - scripts/travis/docker.sh rocproject/travis-ubuntu:14.04 scripts/travis/linux-x86_64/ubuntu-14.04.sh
        - scripts/travis/docker.sh rocproject/travis-debian scripts/travis/linux-x86_64/debian.sh
        - scripts/travis/docker.sh rocproject/travis-fedora scripts/travis/linux-x86_64/fedora.sh
        - scripts/travis/docker.sh rocproject/travis-centos scripts/travis/linux-x86_64/centos.sh
        - scripts/travis/docker.sh rocproject/travis-archlinux scripts/travis/linux-x86_64/archlinux.sh
        - scripts/travis/docker.sh rocproject/travis-min scripts/travis/linux-x86_64/min.sh
        - cat build.status

    - name: "Linux ARM"
      stage: Build
      os: linux
      dist: trusty
      sudo: required
      services:
        - docker
      before_install:
        - docker pull rocproject/cross-arm-bcm2708hardfp-linux-gnueabi:gcc-4.7
        - docker pull rocproject/cross-arm-linux-gnueabihf:gcc-4.9
        - docker pull rocproject/cross-aarch64-linux-gnu:gcc-7.4
      script:
        - scripts/travis/docker.sh rocproject/cross-arm-bcm2708hardfp-linux-gnueabi:gcc-4.7 scripts/travis/linux-arm/arm-bcm2708hardfp-linux-gnueabi.sh
        - scripts/travis/docker.sh rocproject/cross-arm-linux-gnueabihf:gcc-4.9 scripts/travis/linux-arm/arm-linux-gnueabihf.sh
        - scripts/travis/docker.sh rocproject/cross-aarch64-linux-gnu:gcc-7.4 scripts/travis/linux-arm/aarch64-linux-gnu.sh
        - cat build.status

    - name: "macOS Xcode 7.3"
      stage: Build
      os: osx
      osx_image: xcode7.3
      script:
        - scripts/travis/macos/xcode-7.3.sh
      after_failure:
        - cat config.log

    - name: "macOS Xcode 9.1"
      os: osx
      osx_image: xcode9.1
      script:
        - scripts/travis/macos/xcode-9.1.sh
      after_failure:
        - cat config.log

    - name: "macOS Xcode 10.2"
      os: osx
      osx_image: xcode10.2
      script:
        - scripts/travis/macos/xcode-10.2.sh
      after_failure:
        - cat config.log

    - name: "roc-project.github.io"
      stage: Docs
      script:
        - scripts/travis/trigger.sh roc-project%2Froc-project.github.io travis
